export const restaurantData = [
  {
    id: "1",
    name: "Pizza Hub",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591",
    cuisine: "Italian, Pizza",
    rating: 4.6,
    deliveryTime: "20-30 min",
    priceForTwo: 499,
    distance: "2.1 km",
    isVeg: false,
    description:
      "Popular for authentic pizzas, cheesy sides, and baked specials.",
    menu: [
      {
        id: "101",
        name: "Margherita Pizza",
        image: "https://images.unsplash.com/photo-1604382355076-af4b0eb60143",
        description: "Classic mozzarella cheese pizza with tomato basil sauce.",
        price: 249,
        rating: 4.5,
        category: "Pizza",
        isVeg: true,
      },
      {
        id: "102",
        name: "Farmhouse Pizza",
        image: "https://images.unsplash.com/photo-1594007654729-407eedc4be65",
        description:
          "Veg-loaded pizza with mushrooms, onion, capsicum, and cheese.",
        price: 349,
        rating: 4.7,
        category: "Pizza",
        isVeg: true,
      },
      {
        id: "103",
        name: "Pepperoni Pizza",
        image: "https://images.unsplash.com/photo-1628840042765-356cda07504e",
        description: "Loaded pepperoni pizza with rich mozzarella.",
        price: 449,
        rating: 4.8,
        category: "Pizza",
        isVeg: false,
      },
      {
        id: "104",
        name: "Garlic Bread",
        image:
          "https://plus.unsplash.com/premium_photo-1711752902734-a36167479983?q=80&w=688&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        description: "Toasted garlic bread with herbs and butter.",
        price: 149,
        rating: 4.3,
        category: "Sides",
        isVeg: true,
      },
      {
        id: "105",
        name: "White Sauce Pasta",
        image: "https://images.unsplash.com/photo-1645112411341-6c4fd023714a",
        description: "Creamy alfredo pasta with parmesan.",
        price: 299,
        rating: 4.4,
        category: "Pasta",
        isVeg: true,
      },
    ],
  },
  {
    id: "2",
    name: "Burger Town",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd",
    cuisine: "American, Burgers",
    rating: 4.4,
    deliveryTime: "15-25 min",
    priceForTwo: 399,
    distance: "1.4 km",
    isVeg: false,
    description: "Loaded burgers, crispy fries, and grilled specials.",
    menu: [
      {
        id: "201",
        name: "Classic Veg Burger",
        image: "https://images.unsplash.com/photo-1550547660-d9450f859349",
        description: "Crunchy veg patty burger with lettuce and mayo.",
        price: 149,
        rating: 4.2,
        category: "Burger",
        isVeg: true,
      },
      {
        id: "202",
        name: "Chicken Cheese Burger",
        image: "https://images.unsplash.com/photo-1565299507177-b0ac66763828",
        description: "Juicy chicken burger with melted cheese.",
        price: 249,
        rating: 4.6,
        category: "Burger",
        isVeg: false,
      },
      {
        id: "203",
        name: "Loaded Fries",
        image: "https://images.unsplash.com/photo-1576107232684-1279f390859f",
        description: "Crispy fries topped with cheese sauce.",
        price: 129,
        rating: 4.3,
        category: "Sides",
        isVeg: true,
      },
      {
        id: "204",
        name: "Chicken Nuggets",
        image: "https://images.unsplash.com/photo-1562967914-608f82629710",
        description: "Crunchy fried chicken nuggets.",
        price: 179,
        rating: 4.4,
        category: "Snacks",
        isVeg: false,
      },
    ],
  },
  {
    id: "3",
    name: "Spice Route",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe",
    cuisine: "Indian, North Indian",
    rating: 4.8,
    deliveryTime: "30-40 min",
    priceForTwo: 599,
    distance: "3.2 km",
    isVeg: true,
    description: "Traditional Indian curries, biryani, and breads.",
    menu: [
      {
        id: "301",
        name: "Paneer Butter Masala",
        image: "https://images.unsplash.com/photo-1631452180519-c014fe946946",
        description: "Paneer cubes in creamy tomato gravy.",
        price: 279,
        rating: 4.8,
        category: "Main Course",
        isVeg: true,
      },
      {
        id: "302",
        name: "Veg Biryani",
        image: "https://images.unsplash.com/photo-1563379091339-03246963d51a",
        description: "Fragrant basmati rice cooked with spices and vegetables.",
        price: 249,
        rating: 4.6,
        category: "Biryani",
        isVeg: true,
      },
      {
        id: "303",
        name: "Butter Naan",
        image: "https://images.unsplash.com/photo-1601050690597-df0568f70950",
        description: "Fresh buttery naan baked in tandoor.",
        price: 49,
        rating: 4.4,
        category: "Bread",
        isVeg: true,
      },
      {
        id: "304",
        name: "Dal Tadka",
        image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d",
        description: "Yellow lentils tempered with Indian spices.",
        price: 199,
        rating: 4.5,
        category: "Main Course",
        isVeg: true,
      },
    ],
  },
  {
    id: "4",
    name: "Sushi Zen",
    image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c",
    cuisine: "Japanese, Sushi",
    rating: 4.5,
    deliveryTime: "35-45 min",
    priceForTwo: 899,
    distance: "4.1 km",
    isVeg: false,
    description: "Fresh sushi rolls and Japanese favorites.",
    menu: [
      {
        id: "401",
        name: "Salmon Sushi Roll",
        image: "https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56",
        description: "Fresh salmon sushi with seasoned rice.",
        price: 499,
        rating: 4.7,
        category: "Sushi",
        isVeg: false,
      },
      {
        id: "402",
        name: "Veg Sushi Roll",
        image: "https://images.unsplash.com/photo-1611143669185-af224c5e3252",
        description: "Vegetarian sushi with avocado and cucumber.",
        price: 349,
        rating: 4.4,
        category: "Sushi",
        isVeg: true,
      },
    ],
  },
  {
    id: "5",
    name: "Taco Fiesta",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38",
    cuisine: "Mexican, Tacos",
    rating: 4.3,
    deliveryTime: "20-30 min",
    priceForTwo: 549,
    distance: "2.7 km",
    isVeg: false,
    description: "Authentic Mexican tacos, burritos, and loaded bowls.",
    menu: [
      {
        id: "501",
        name: "Chicken Taco",
        image: "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85",
        description: "Soft taco loaded with grilled chicken.",
        price: 199,
        rating: 4.5,
        category: "Tacos",
        isVeg: false,
      },
      {
        id: "502",
        name: "Veg Burrito",
        image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f",
        description: "Stuffed burrito with beans, rice, and veggies.",
        price: 249,
        rating: 4.3,
        category: "Burrito",
        isVeg: true,
      },
      {
        id: "503",
        name: "Nachos Supreme",
        image: "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d",
        description: "Loaded nachos with salsa and cheese.",
        price: 179,
        rating: 4.4,
        category: "Snacks",
        isVeg: true,
      },
    ],
  },
  {
    id: "6",
    name: "Wok Express",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4",
    cuisine: "Chinese, Asian",
    rating: 4.5,
    deliveryTime: "25-35 min",
    priceForTwo: 549,
    distance: "2.9 km",
    isVeg: false,
    description: "Fast Asian bowls, noodles, and wok specials.",
    menu: [
      {
        id: "601",
        name: "Hakka Noodles",
        image: "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841",
        description: "Classic stir-fried noodles with vegetables.",
        price: 199,
        rating: 4.4,
        category: "Noodles",
        isVeg: true,
      },
      {
        id: "602",
        name: "Chicken Fried Rice",
        image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b",
        description: "Wok tossed rice with chicken and sauces.",
        price: 249,
        rating: 4.6,
        category: "Rice",
        isVeg: false,
      },
      {
        id: "603",
        name: "Spring Rolls",
        image: "https://images.unsplash.com/photo-1603360946369-dc9bb6258143",
        description: "Crispy vegetable spring rolls.",
        price: 149,
        rating: 4.3,
        category: "Starters",
        isVeg: true,
      },
    ],
  },
  {
    id: "7",
    name: "Dosa Palace",
    image: "https://images.unsplash.com/photo-1630383249896-424e482df921",
    cuisine: "South Indian",
    rating: 4.7,
    deliveryTime: "20-30 min",
    priceForTwo: 349,
    distance: "1.8 km",
    isVeg: true,
    description: "Authentic dosas, idlis, and South Indian meals.",
    menu: [
      {
        id: "701",
        name: "Masala Dosa",
        image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976",
        description: "Crispy dosa stuffed with spiced potato filling.",
        price: 149,
        rating: 4.8,
        category: "Dosa",
        isVeg: true,
      },
      {
        id: "702",
        name: "Idli Sambar",
        image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0",
        description: "Soft steamed idlis served with sambar.",
        price: 99,
        rating: 4.5,
        category: "Breakfast",
        isVeg: true,
      },
      {
        id: "703",
        name: "Medu Vada",
        image: "https://images.unsplash.com/photo-1626132647523-66c8d3f3c6f1",
        description: "Crispy lentil doughnuts with chutney.",
        price: 119,
        rating: 4.4,
        category: "Snacks",
        isVeg: true,
      },
    ],
  },
  {
    id: "8",
    name: "Cafe Mocha",
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24",
    cuisine: "Cafe, Desserts",
    rating: 4.4,
    deliveryTime: "15-25 min",
    priceForTwo: 599,
    distance: "1.2 km",
    isVeg: true,
    description: "Coffee, desserts, and cafe comfort food.",
    menu: [
      {
        id: "801",
        name: "Cappuccino",
        image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93",
        description: "Freshly brewed creamy cappuccino.",
        price: 149,
        rating: 4.5,
        category: "Beverage",
        isVeg: true,
      },
      {
        id: "802",
        name: "Chocolate Brownie",
        image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c",
        description: "Warm gooey chocolate brownie.",
        price: 179,
        rating: 4.7,
        category: "Dessert",
        isVeg: true,
      },
      {
        id: "803",
        name: "Veg Sandwich",
        image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af",
        description: "Toasted sandwich with veggies and cheese.",
        price: 199,
        rating: 4.3,
        category: "Snacks",
        isVeg: true,
      },
    ],
  },
  {
    id: "9",
    name: "Green Bowl",
    image: "https://images.unsplash.com/photo-1547592180-85f173990554",
    cuisine: "Healthy, Salads",
    rating: 4.6,
    deliveryTime: "15-20 min",
    priceForTwo: 499,
    distance: "1.6 km",
    isVeg: true,
    description: "Healthy bowls, salads, and clean eating meals.",
    menu: [
      {
        id: "901",
        name: "Caesar Salad",
        image: "https://images.unsplash.com/photo-1546793665-c74683f339c1",
        description: "Fresh romaine lettuce with dressing.",
        price: 229,
        rating: 4.4,
        category: "Salad",
        isVeg: true,
      },
      {
        id: "902",
        name: "Protein Bowl",
        image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
        description: "Healthy quinoa bowl with vegetables.",
        price: 299,
        rating: 4.7,
        category: "Healthy Bowl",
        isVeg: true,
      },
    ],
  },
  {
    id: "10",
    name: "Arabian Nights",
    image: "https://images.unsplash.com/photo-1552566626-52f8b828add9",
    cuisine: "Middle Eastern",
    rating: 4.5,
    deliveryTime: "30-40 min",
    priceForTwo: 799,
    distance: "4.4 km",
    isVeg: false,
    description: "Authentic shawarmas, kebabs, and Arabic platters.",
    menu: [
      {
        id: "1001",
        name: "Chicken Shawarma",
        image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783",
        description: "Loaded shawarma wrap with garlic sauce.",
        price: 249,
        rating: 4.7,
        category: "Wraps",
        isVeg: false,
      },
      {
        id: "1002",
        name: "Falafel Platter",
        image: "https://images.unsplash.com/photo-1541592106381-b31e9677c0e5",
        description: "Crispy falafel served with hummus.",
        price: 299,
        rating: 4.4,
        category: "Platter",
        isVeg: true,
      },
    ],
  },
  {
    id: "11",
    name: "Thai Twist",
    image: "https://images.unsplash.com/photo-1552566626-52f8b828add9",
    cuisine: "Thai",
    rating: 4.6,
    deliveryTime: "25-35 min",
    priceForTwo: 749,
    distance: "3.1 km",
    isVeg: false,
    description: "Authentic Thai curries, noodles, and stir-fried specials.",
    menu: [
      {
        id: "1101",
        name: "Pad Thai",
        image: "https://images.unsplash.com/photo-1559314809-0f31657def5e",
        description:
          "Classic Thai stir-fried noodles with peanuts and vegetables.",
        price: 329,
        rating: 4.7,
        category: "Noodles",
        isVeg: true,
      },
      {
        id: "1102",
        name: "Green Thai Curry",
        image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd",
        description: "Spicy Thai green curry with vegetables and coconut milk.",
        price: 379,
        rating: 4.6,
        category: "Curry",
        isVeg: true,
      },
      {
        id: "1103",
        name: "Chicken Satay",
        image: "https://images.unsplash.com/photo-1604908176997-43198c5d8b7b",
        description: "Grilled chicken skewers with peanut sauce.",
        price: 349,
        rating: 4.5,
        category: "Starter",
        isVeg: false,
      },
    ],
  },
  {
    id: "12",
    name: "Seoul Bites",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5",
    cuisine: "Korean",
    rating: 4.5,
    deliveryTime: "30-40 min",
    priceForTwo: 899,
    distance: "4.0 km",
    isVeg: false,
    description: "Korean street food, BBQ, and spicy bowls.",
    menu: [
      {
        id: "1201",
        name: "Kimchi Fried Rice",
        image: "https://images.unsplash.com/photo-1512058564366-18510be2db19",
        description: "Spicy fried rice with kimchi and egg.",
        price: 299,
        rating: 4.5,
        category: "Rice",
        isVeg: false,
      },
      {
        id: "1202",
        name: "Korean BBQ Chicken",
        image: "https://images.unsplash.com/photo-1608039755401-742074f0548d",
        description: "Sweet and spicy Korean grilled chicken.",
        price: 449,
        rating: 4.7,
        category: "BBQ",
        isVeg: false,
      },
      {
        id: "1203",
        name: "Tteokbokki",
        image: "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f",
        description: "Spicy Korean rice cakes in gochujang sauce.",
        price: 279,
        rating: 4.4,
        category: "Street Food",
        isVeg: true,
      },
    ],
  },
  {
    id: "13",
    name: "Urban Plate",
    image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b",
    cuisine: "Continental",
    rating: 4.4,
    deliveryTime: "20-30 min",
    priceForTwo: 699,
    distance: "2.5 km",
    isVeg: false,
    description: "Modern continental dishes and premium comfort meals.",
    menu: [
      {
        id: "1301",
        name: "Grilled Chicken Steak",
        image: "https://images.unsplash.com/photo-1544025162-d76694265947",
        description: "Tender grilled chicken steak with mashed potatoes.",
        price: 499,
        rating: 4.6,
        category: "Main Course",
        isVeg: false,
      },
      {
        id: "1302",
        name: "Creamy Mushroom Pasta",
        image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9",
        description: "Creamy pasta with sautéed mushrooms.",
        price: 349,
        rating: 4.4,
        category: "Pasta",
        isVeg: true,
      },
    ],
  },
  {
    id: "14",
    name: "Biryani House",
    image: "https://images.unsplash.com/photo-1563379091339-03246963d51a",
    cuisine: "Biryani",
    rating: 4.8,
    deliveryTime: "30-45 min",
    priceForTwo: 649,
    distance: "3.6 km",
    isVeg: false,
    description: "Flavor-packed biryanis and Mughlai favorites.",
    menu: [
      {
        id: "1401",
        name: "Chicken Dum Biryani",
        image: "https://images.unsplash.com/photo-1701579231305-d84d8af9a3fd",
        description: "Traditional dum-cooked chicken biryani.",
        price: 349,
        rating: 4.8,
        category: "Biryani",
        isVeg: false,
      },
      {
        id: "1402",
        name: "Paneer Biryani",
        image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0",
        description: "Spiced paneer biryani with aromatic rice.",
        price: 299,
        rating: 4.5,
        category: "Biryani",
        isVeg: true,
      },
    ],
  },
  {
    id: "15",
    name: "Chaat Junction",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950",
    cuisine: "Street Food",
    rating: 4.5,
    deliveryTime: "15-20 min",
    priceForTwo: 299,
    distance: "1.1 km",
    isVeg: true,
    description: "Indian street food favorites served fresh.",
    menu: [
      {
        id: "1501",
        name: "Pani Puri",
        image: "https://images.unsplash.com/photo-1626132647523-66c8d3f3c6f1",
        description: "Crispy puris filled with spicy tangy water.",
        price: 99,
        rating: 4.6,
        category: "Street Food",
        isVeg: true,
      },
      {
        id: "1502",
        name: "Sev Puri",
        image: "https://images.unsplash.com/photo-1596797038530-2c107229654b",
        description: "Crunchy puris topped with chutneys and sev.",
        price: 119,
        rating: 4.4,
        category: "Street Food",
        isVeg: true,
      },
    ],
  },
  {
    id: "16",
    name: "Ocean Catch",
    image: "https://images.unsplash.com/photo-1559847844-5315695dadae",
    cuisine: "Seafood",
    rating: 4.7,
    deliveryTime: "30-45 min",
    priceForTwo: 1099,
    distance: "5.2 km",
    isVeg: false,
    description:
      "Fresh seafood platters, grilled fish, and premium coastal dishes.",
    menu: [
      {
        id: "1601",
        name: "Grilled Salmon",
        image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288",
        description: "Perfectly grilled salmon fillet with herbs and butter.",
        price: 599,
        rating: 4.8,
        category: "Main Course",
        isVeg: false,
      },
      {
        id: "1602",
        name: "Fish & Chips",
        image: "https://images.unsplash.com/photo-1544982503-9f984c14501a",
        description: "Crispy battered fish served with fries.",
        price: 449,
        rating: 4.6,
        category: "Main Course",
        isVeg: false,
      },
      {
        id: "1603",
        name: "Prawn Tempura",
        image: "https://images.unsplash.com/photo-1625943555419-56a2cb596640",
        description: "Golden fried crispy prawns.",
        price: 399,
        rating: 4.5,
        category: "Starter",
        isVeg: false,
      },
    ],
  },
  {
    id: "17",
    name: "Plant Fuel",
    image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061",
    cuisine: "Vegan",
    rating: 4.6,
    deliveryTime: "20-30 min",
    priceForTwo: 599,
    distance: "2.3 km",
    isVeg: true,
    description: "Healthy plant-based meals, smoothies, and protein bowls.",
    menu: [
      {
        id: "1701",
        name: "Vegan Buddha Bowl",
        image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
        description: "Quinoa, avocado, chickpeas, and fresh vegetables.",
        price: 349,
        rating: 4.7,
        category: "Healthy Bowl",
        isVeg: true,
      },
      {
        id: "1702",
        name: "Vegan Burger",
        image: "https://images.unsplash.com/photo-1520072959219-c595dc870360",
        description: "Plant-based patty burger with lettuce and sauce.",
        price: 299,
        rating: 4.5,
        category: "Burger",
        isVeg: true,
      },
      {
        id: "1703",
        name: "Green Smoothie",
        image: "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4",
        description: "Spinach, banana, and almond milk smoothie.",
        price: 199,
        rating: 4.4,
        category: "Beverage",
        isVeg: true,
      },
    ],
  },
  {
    id: "18",
    name: "Sweet Crumbs",
    image: "https://images.unsplash.com/photo-1555507036-ab794f4afe5a",
    cuisine: "Bakery",
    rating: 4.5,
    deliveryTime: "15-25 min",
    priceForTwo: 499,
    distance: "1.7 km",
    isVeg: true,
    description: "Fresh cakes, pastries, cookies, and bakery delights.",
    menu: [
      {
        id: "1801",
        name: "Chocolate Cake",
        image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587",
        description: "Rich chocolate layered cake.",
        price: 299,
        rating: 4.8,
        category: "Dessert",
        isVeg: true,
      },
      {
        id: "1802",
        name: "Croissant",
        image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a",
        description: "Buttery flaky croissant.",
        price: 149,
        rating: 4.4,
        category: "Bakery",
        isVeg: true,
      },
      {
        id: "1803",
        name: "Blueberry Muffin",
        image: "https://images.unsplash.com/photo-1607958996333-41aef7caefaa",
        description: "Soft muffin packed with blueberries.",
        price: 129,
        rating: 4.5,
        category: "Dessert",
        isVeg: true,
      },
    ],
  },
  {
    id: "19",
    name: "Punjab Grill",
    image: "https://images.unsplash.com/photo-1517244683847-7456b63c5969",
    cuisine: "Punjabi",
    rating: 4.8,
    deliveryTime: "30-40 min",
    priceForTwo: 799,
    distance: "3.4 km",
    isVeg: false,
    description:
      "Punjabi curries, tandoori dishes, and rich North Indian meals.",
    menu: [
      {
        id: "1901",
        name: "Butter Chicken",
        image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398",
        description: "Creamy butter chicken cooked in rich tomato gravy.",
        price: 399,
        rating: 4.9,
        category: "Main Course",
        isVeg: false,
      },
      {
        id: "1902",
        name: "Paneer Tikka",
        image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8",
        description: "Chargrilled paneer cubes with Indian spices.",
        price: 299,
        rating: 4.6,
        category: "Starter",
        isVeg: true,
      },
      {
        id: "1903",
        name: "Garlic Naan",
        image: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a",
        description: "Fresh naan topped with garlic butter.",
        price: 79,
        rating: 4.5,
        category: "Bread",
        isVeg: true,
      },
    ],
  },
  {
    id: "20",
    name: "Snack Stop",
    image: "https://images.unsplash.com/photo-1565299507177-b0ac66763828",
    cuisine: "Fast Food",
    rating: 4.4,
    deliveryTime: "10-20 min",
    priceForTwo: 349,
    distance: "1.0 km",
    isVeg: false,
    description: "Quick fast food favorites, wraps, fries, and drinks.",
    menu: [
      {
        id: "2001",
        name: "Chicken Wrap",
        image: "https://images.unsplash.com/photo-1530469912745-a215c6b256ea",
        description: "Juicy grilled chicken wrap with fresh veggies.",
        price: 199,
        rating: 4.5,
        category: "Wrap",
        isVeg: false,
      },
      {
        id: "2002",
        name: "Cheese Fries",
        image: "https://images.unsplash.com/photo-1576107232684-1279f390859f",
        description: "Crispy fries loaded with melted cheese.",
        price: 149,
        rating: 4.3,
        category: "Sides",
        isVeg: true,
      },
      {
        id: "2003",
        name: "Cold Coffee",
        image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735",
        description: "Refreshing chilled creamy coffee.",
        price: 129,
        rating: 4.4,
        category: "Beverage",
        isVeg: true,
      },
    ],
  },
];
